const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('api', {
  platform: process.platform,
  openProject: () => ipcRenderer.invoke('open-project'),
  reloadProject: () => ipcRenderer.invoke('reload-project'),
  undo: () => ipcRenderer.invoke('undo'),
  redo: () => ipcRenderer.invoke('redo'),
  undoStatus: () => ipcRenderer.invoke('undo-status'),
  saveSpriteConfig: (config) => ipcRenderer.invoke('save-sprite-config', config),
  saveSoundsJson: (data) => ipcRenderer.invoke('save-sounds-json', data),
  saveSettings: (data) => ipcRenderer.invoke('save-settings', data),
  runScript: (name) => ipcRenderer.invoke('run-script', name),
  runDeploy: (name) => ipcRenderer.invoke('run-deploy', name),
  onScriptOutput: (cb) => ipcRenderer.on('script-output', cb),
  offScriptOutput: (cb) => ipcRenderer.removeListener('script-output', cb),
  cleanDist: () => ipcRenderer.invoke('clean-dist'),
  gitStatus: () => ipcRenderer.invoke('git-status'),
  gitCommitPush: (message) => ipcRenderer.invoke('git-commit-push', message),
  importSounds: () => ipcRenderer.invoke('import-sounds'),
  readAudioFile: (filename) => ipcRenderer.invoke('read-audio-file', filename),
  deleteSound: (filename) => ipcRenderer.invoke('delete-sound', filename),
  restoreSound: (filename) => ipcRenderer.invoke('restore-sound', filename),
  listDeletedSounds: () => ipcRenderer.invoke('list-deleted-sounds'),
  // Template & health
  healthCheck: () => ipcRenderer.invoke('health-check'),
  initFromTemplate: (opts) => ipcRenderer.invoke('init-from-template', opts),
  npmInstall: () => ipcRenderer.invoke('npm-install'),
  // Game configuration
  pickGameRepo: () => ipcRenderer.invoke('pick-game-repo'),
  configureGame: (config) => ipcRenderer.invoke('configure-game', config),
  yarnInstallGame: () => ipcRenderer.invoke('yarn-install-game'),
  // Game launch
  getGameScripts: () => ipcRenderer.invoke('get-game-scripts'),
  pullGameJson: () => ipcRenderer.invoke('pull-game-json'),
  buildGame: () => ipcRenderer.invoke('build-game'),
  runGameScript: (name) => ipcRenderer.invoke('run-game-script', name),
  killGame: () => ipcRenderer.invoke('kill-game'),
  stopAll: () => ipcRenderer.invoke('stop-all'),
  openUrl: (url) => ipcRenderer.invoke('open-url', url),
  openFolder: (relPath) => ipcRenderer.invoke('open-folder', relPath),
  listEncoderTest: () => ipcRenderer.invoke('list-encoder-test'),
  upgradeFfmpeg: () => ipcRenderer.invoke('upgrade-ffmpeg'),
  vpnConnect: () => ipcRenderer.invoke('vpn-connect'),
  vpnDisconnect: () => ipcRenderer.invoke('vpn-disconnect'),
  vpnStatus: () => ipcRenderer.invoke('vpn-status'),
  openGameWindow: (url) => ipcRenderer.invoke('open-game-window', url),
  waitForPort: (opts) => ipcRenderer.invoke('wait-for-port', opts),
  gitPullGame: () => ipcRenderer.invoke('git-pull-game'),
  checkoutGameBranch: (branch) => ipcRenderer.invoke('checkout-game-branch', branch),
  // Pool measurement
  measurePool: (opts) => ipcRenderer.invoke('measure-pool', opts),
  // Orphan analysis
  analyzeOrphans: () => ipcRenderer.invoke('analyze-orphans'),
  cleanOrphans: () => ipcRenderer.invoke('clean-orphans'),
  // Game hook scanner
  scanGameHooks: () => ipcRenderer.invoke('scan-game-hooks'),
  // Game repo git
  gameGitStatus: () => ipcRenderer.invoke('game-git-status'),
  gameGitCreateBranchCommitPush: (opts) => ipcRenderer.invoke('game-git-create-branch-commit-push', opts),
  gameGitCreatePr: (opts) => ipcRenderer.invoke('game-git-create-pr', opts),
  getGameBuildVersion: (opts) => ipcRenderer.invoke('get-game-build-version', opts),
});
